# Generated by Django 6.0.5 on 2026-06-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bikeuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('driving_license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(choices=[('Customer', 'Customer'), ('Staff', 'Staff'), ('Admin', 'Admin')], default='Customer', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='motorbike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_make', models.CharField(max_length=20)),
                ('bike_model', models.CharField(max_length=10)),
                ('bike_year', models.CharField(max_length=10)),
                ('bike_imgsrc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tblmotorbike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_make', models.CharField(max_length=20)),
                ('bike_model', models.CharField(max_length=10)),
                ('bike_year', models.CharField(max_length=10)),
                ('bike_price', models.CharField(blank=True, max_length=10, null=True)),
                ('bike_imgsrc', models.TextField()),
                ('bike_plate_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('bike_status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('bike_daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
    ]
