# Generated by Django 6.0.5 on 2026-06-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorbike_rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikeuser',
            name='password',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bikeuser',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
