# Generated by Django 4.2.29 on 2026-04-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorbike_rental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblmotorbike',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('bike_make', models.CharField(max_length=20)),
                ('bike_model', models.CharField(max_length=10)),
                ('bike_year', models.CharField(max_length=10)),
                ('bike_price', models.CharField(
                    blank=True,
                    max_length=10,
                    null=True
                )),
                ('bike_imgsrc', models.TextField(max_length=200)),
                ('bike_plate_number', models.CharField(
                    blank=True,
                    max_length=50,
                    null=True,
                    unique=True
                )),
                ('bike_status', models.CharField(
                    default='Available',
                    max_length=20,
                    choices=[
                        ('Available', 'Available'),
                        ('Rented', 'Rented'),
                        ('Maintenance', 'Maintenance')
                    ]
                )),
                ('bike_daily_rate', models.DecimalField(
                    blank=True,
                    decimal_places=2,
                    max_digits=6,
                    null=True
                )),
            ],
        ),
    ]
