# Generated by Django 4.2.29 on 2026-05-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorbike_rental', '0002_tblmotorbike'),
    ]

    operations = [
        migrations.CreateModel(
            name='motorbike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_make', models.CharField(max_length=20)),
                ('bike_model', models.CharField(max_length=10)),
                ('bike_year', models.CharField(max_length=10)),
                ('bike_imgsrc', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tblmotorbike',
            name='bike_imgsrc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tblmotorbike',
            name='bike_status',
            field=models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'Maintenance')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='tblmotorbike',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
