# Generated by Django 6.0.5 on 2026-06-17 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorbike_rental', '0002_bikeuser_password_bikeuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikeuser',
            old_name='driving_license_number',
            new_name='driving_licence_number',
        ),
    ]
