# Generated by Django 6.0.5 on 2026-07-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorbike_rental', '0005_booking_age_verified_booking_identity_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hiring_status',
            field=models.CharField(choices=[('request', 'Request'), ('verification', 'Verification'), ('confirmation', 'Confirmed'), ('ready', 'Ready'), ('collection', 'Collection'), ('completion', 'Completion')], default='Request', max_length=20),
        ),
    ]
