# Generated by Django 6.0.5 on 2026-07-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorbike_rental', '0006_booking_hiring_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hiring_status',
            field=models.CharField(choices=[('request', 'Request'), ('verification', 'Verification'), ('confirmation', 'Confirmation'), ('ready', 'Ready'), ('collection', 'Collection'), ('completion', 'Completion')], default='Request', max_length=20),
        ),
    ]
