# Generated by Django 6.0.5 on 2026-07-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorbike_rental', '0007_alter_booking_hiring_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='customer',
            new_name='rentaluser',
        ),
        migrations.AlterField(
            model_name='booking',
            name='hiring_status',
            field=models.CharField(choices=[('request', 'Request'), ('verification', 'Verification'), ('confirmation', 'Confirmation'), ('ready', 'Ready'), ('collection', 'Collection'), ('completion', 'Completion')], default='request', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
