# Generated by Django 6.0.5 on 2026-07-18 23:43

import motorbike_rental.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorbike_rental', '0009_booking_booking_reference_booking_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(default=motorbike_rental.models.generate_booking_reference, editable=False, max_length=20, null=True),
        ),
    ]
