# Generated by Django 6.0.5 on 2026-07-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorbike_rental', '0010_alter_booking_booking_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
