# Generated by Django 6.0.5 on 2026-07-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorbike_rental', '0011_remove_booking_status_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('preparing', 'Preparing'), ('ready', 'Ready for Collection'), ('active', 'Active Hire'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
