"""
Django settings for motorbikesite project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/

"""

from pathlib import Path
from decouple import config

import dj_database_url
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

'''
SECRET_KEY = (
    'django-insecure-fg67%p7g4!s=)o%)#3&qqh4md&fs53yj0ozzb^9md*c*31*#8)'
)
'''
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-development-key"
)

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True

'''
ALLOWED_HOSTS = []
'''

'''
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".herokuapp.com",
]
'''
# Replace lines 54-58 with this:
ALLOWED_HOSTS = [
    'localhost', 
    '127.0.0.1', 
    '.herokuapp.com'  # The dot prefix automatically matches all Heroku app subdomains
]
# In settings.py
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')


#AUTH_USER_MODEL = 'motorbike_rental.User'

# Application definition

INSTALLED_APPS = [
    'motorbike_rental.apps.PollsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',   
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'motorbikesite.urls'
#AUTH_USER_MODEL = 'motorbike_rental.user'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'motorbikesite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DEBUG = config("DEBUG", default=False, cast=bool)

if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': "django.db.backends.postgresql",
            'NAME': config("DB_NAME", default="dummy_db_name"),
            'USER': config("DB_USER", default="dummy_user"),
            'PASSWORD': config("DB_PASSWORD", default="dummy_password"),
            'HOST': config("DB_HOST", default="localhost"),
            'PORT': config("DB_PORT", default="5432")
        }
    }

else:
    DATABASES = {
        "default": dj_database_url.config(
           # If DATABASE_URL isn't found (like locally), it falls back to your local dbBike configuration
           default=(
               f"postgresql://{config('DB_USER', default='postgres')}:"
               f"{config('DB_PASSWORD', default='')}@"
               f"{config('DB_HOST', default='localhost')}:"
               f"{config('DB_PORT', default='5432')}/dbBike"
           )
        )
    }

    '''
    DATABASES = {
        "default": dj_database_url.config(
            conn_max_age=600,
            ssl_require=True
        )
    }
    ''' 

'''
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config("DB_NAME"),
            "USER": config("DB_USER"),
            "PASSWORD": config("DB_PASSWORD"),
            "HOST": config("DB_HOST"),
            "PORT": config("DB_PORT"),
        }
    }
'''

'''
DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get(
            "DATABASE_URL"
        )
    )
}
'''



'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
'''

'''
DATABASES = {
    'default': {
      'ENGINE': 'django.db.backends.postgresql',
      'USER': 'postgres',
      'PASSWORD': 'mosta',
      'HOST': 'localhost',
      'PORT': '5432',
      'NAME': 'dbBike',
    }
}

'''

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator'
        ),
    },
    {
        # shortened name to satisfy line-length linting
        'NAME': (
            'django.contrib.auth.password_validation.'
            'MinimumLengthValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'CommonPasswordValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'NumericPasswordValidator'
        ),
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

#TIME_ZONE = 'UTC'
TIME_ZONE = 'Europe/London'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

'''
STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / "staticfiles"

'''

# Session disappears completely when the browser tab/window is closed
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# Forces Django to save session parameters to the database on every single request
SESSION_SAVE_EVERY_REQUEST = True